version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    tf_cnn_benchmarks:
      image: deephdc/deep-oc-tf_cnn_benchmarks
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    tf_cnn_benchmarks-gpu:
      image: deephdc/deep-oc-tf_cnn_benchmarks:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    tf_cnn_benchmarks-rclone:
      extends:
        service: tf_cnn_benchmarks
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
